FROM golang:1.23 AS build

WORKDIR /app

COPY . .

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/main .
COPY --from=build /app/config.yaml .
COPY --from=build /app/.aws /root/.aws

EXPOSE 8080

CMD ["./main"]