FROM golang:1.23 AS build

WORKDIR /app

COPY . .

RUN go mod tidy
RUN go build -o main

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/main .
COPY --from=build /app/config.yaml .
COPY --from=build /app/.aws ./.aws

EXPOSE 8080

CMD ["./main"]